import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { GetObjectCommand, S3Client } from '@aws-sdk/client-s3'
import { postIndexSchema, postSchema, type Post } from '@nexsift/schemas/post'
import { topicSchema } from '@nexsift/schemas/topic'

const signalsPerTopic = 3
const root = process.cwd()
const imagesDirectory = path.join(root, 'web/public/images')
const outputFile = path.join(root, 'web/src/content/signals.ts')

const region = process.env.AWS_REGION ?? 'us-east-1'
const bucket = process.env.CONTENT_BUCKET ?? 'nexsift-content-prod'
const client = new S3Client({ region })

async function readJson(key: string): Promise<unknown> {
  const response = await client.send(new GetObjectCommand({ Bucket: bucket, Key: key }))
  if (!response.Body) throw new Error(`S3 object ${key} has no body`)
  return JSON.parse(await response.Body.transformToString()) as unknown
}

async function readBytes(key: string): Promise<Buffer> {
  const response = await client.send(new GetObjectCommand({ Bucket: bucket, Key: key }))
  if (!response.Body) throw new Error(`S3 object ${key} has no body`)
  return Buffer.from(await response.Body.transformToByteArray())
}

function inlineImageKeys(content: string) {
  const keys: string[] = []
  for (const match of content.matchAll(/\/s3\/(public\/images\/[^\s)"']+)/g)) {
    if (match[1]) keys.push(match[1])
  }
  return keys
}

async function main() {
  const selected: Post[] = []

  for (const topic of topicSchema.options) {
    const index = postIndexSchema.parse(await readJson(`public/indexes/topics/${topic}.json`))
    const top = [...index].sort((first, second) => second.relevanceScore - first.relevanceScore).slice(0, signalsPerTopic)
    for (const summary of top) {
      selected.push(postSchema.parse(await readJson(`public/posts/${summary.slug}.json`)))
    }
  }

  const imageKeys = new Set<string>()
  for (const post of selected) {
    if (post.coverImage) imageKeys.add(post.coverImage.objectKey)
    for (const key of inlineImageKeys(post.content)) imageKeys.add(key)
  }

  await mkdir(imagesDirectory, { recursive: true })
  for (const key of imageKeys) {
    const name = key.slice('public/images/'.length)
    await writeFile(path.join(imagesDirectory, name), await readBytes(key))
  }

  const generated = [
    '// Generated by packages/dev-publish/export-static.ts. Frozen portfolio snapshot.',
    '// Regenerate only when the selected signals change; the site serves these files directly.',
    '',
    `export const signals: unknown[] = ${JSON.stringify(selected, null, 2)}`,
    '',
  ].join('\n')

  await mkdir(path.dirname(outputFile), { recursive: true })
  await writeFile(outputFile, generated)
  console.log(`exported ${selected.length} signals and ${imageKeys.size} images from ${bucket}`)
}

main().catch((error) => {
  console.error('export_failed', error)
  process.exitCode = 1
})
